'use client';
import { useState } from 'react';
import { useAuth } from '@/lib/auth-context';
import { predictAPI } from '@/lib/api';
import { useRouter } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import {
 Activity, Brain, Heart, Moon, BookOpen, Smartphone, Dumbbell, Gauge,
 AlertTriangle, Sparkles, TrendingUp, ArrowRight, ArrowLeft,
 Gamepad2, Users2, ShieldAlert, CheckCircle, ChevronRight
} from 'lucide-react';

const departments = ['Engineering', 'Science', 'Medical', 'Arts', 'Business', 'Law', 'Education', 'Social Sciences'];

const STEPS = [
 { title: 'Clinical Profile', subtitle: 'Demographics & background', icon: Brain, color: '#1e40af' },
 { title: 'Academic Rigor', subtitle: 'Study habits & pressure', icon: BookOpen, color: '#7c3aed' },
 { title: 'Digital Habits', subtitle: 'Screen & gaming patterns', icon: Gamepad2, color: '#ea580c' },
 { title: 'Lifestyle Matrix', subtitle: 'Sleep, exercise & stress', icon: Heart, color: '#059669' },
];

const slideVariants = {
 enter: (dir: number) => ({ x: dir > 0 ? 200 : -200, opacity: 0 }),
 center: { x: 0, opacity: 1 },
 exit: (dir: number) => ({ x: dir > 0 ? -200 : 200, opacity: 0 }),
};

export default function AssessmentPage() {
 const { token } = useAuth();
 const router = useRouter();
 const [wizardStep, setWizardStep] = useState(0);
 const [direction, setDirection] = useState(1);
 const [phase, setPhase] = useState<'form' | 'loading' | 'result'>('form');
 const [result, setResult] = useState<any>(null);
 const [error, setError] = useState('');
 const [form, setForm] = useState({
 age: 20, gender: 'Male', department: 'Engineering',
 cgpa: 3.0, sleep_duration: 7, study_hours: 5,
 social_media_hours: 3, physical_activity: 60, stress_level: 5,
 gaming_hours: 1, gaming_behavior_score: 1, social_media_addiction: 1,
 academic_workload: 5, peer_pressure: 3, exam_anxiety: 4
 });

 const update = (key: string, val: any) => setForm(prev => ({ ...prev, [key]: val }));

 const goNext = () => {
 if (wizardStep < STEPS.length - 1) {
 setDirection(1);
 setWizardStep(s => s + 1);
 }
 };
 const goPrev = () => {
 if (wizardStep > 0) {
 setDirection(-1);
 setWizardStep(s => s - 1);
 }
 };

 const handleSubmit = async () => {
 setPhase('loading');
 setError('');
 try {
 const res = await predictAPI.predict(form, token!);
 setResult(res);
 setPhase('result');
 } catch (err: any) { setError(err.message); setPhase('form'); }
 };

 // ─── Loading State ───
 if (phase === 'loading') {
 return (
 <div className="flex items-center justify-center min-h-[60vh] animate-fade-in-up">
 <div className="text-center max-w-sm mx-auto px-6">
 <div className="w-20 h-20 mx-auto mb-8 rounded-[2rem] bg-[#1e40af]/5 flex items-center justify-center relative">
 <div className="absolute inset-0 rounded-[2rem] border-2 border-[#1e40af]/10 animate-ping opacity-20" />
 <Brain size={40} className="text-[#1e40af]" />
 </div>
 <h2 className="text-2xl font-bold text-slate-900 mb-3">AI Analysis in Progress</h2>
 <p className="text-slate-500 font-light leading-relaxed">Our clinical-grade engine is evaluating your behavioral data against our student mental health model.</p>
 <div className="mt-8 flex justify-center gap-1.5">
 <div className="w-2 h-2 rounded-full bg-[#1e40af] animate-bounce [animation-delay:-0.3s]" />
 <div className="w-2 h-2 rounded-full bg-[#1e40af] animate-bounce [animation-delay:-0.15s]" />
 <div className="w-2 h-2 rounded-full bg-[#1e40af] animate-bounce" />
 </div>
 </div>
 </div>
 );
 }

 // ─── Results View ───
 if (phase === 'result' && result) {
 return (
 <div className="max-w-4xl mx-auto space-y-8 animate-fade-in-up pb-12">
 <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
 <div>
 <h1 className="text-3xl font-bold tracking-tight text-slate-900 mb-1">Assessment Insights</h1>
 <p className="text-slate-500 text-sm font-light">Precision health report generated by SMILE-AI</p>
 </div>
 <div className="px-4 py-2 rounded-xl bg-white border border-slate-200 flex items-center gap-2 self-start sm:self-center">
 <TrendingUp size={16} className="text-[#1e40af]" />
 <span className="text-xs font-bold text-slate-900 uppercase tracking-wider">Stability: 92%</span>
 </div>
 </div>

 <div className={`bg-white/70 backdrop-blur-2xl rounded-[2rem] shadow-[0_8px_40px_-12px_rgba(0,0,0,0.1)] border border-white/60 p-8 relative overflow-hidden group ${result.risk_level === 'low' ? 'border-green-100' : result.risk_level === 'moderate' ? 'border-yellow-100' : 'border-red-100'}`}>
 <div className={`absolute top-0 right-0 w-32 h-32 -translate-y-1/2 translate-x-1/2 blur-2xl opacity-10 rounded-full ${result.risk_level === 'low' ? 'bg-green-500' : result.risk_level === 'moderate' ? 'bg-yellow-500' : 'bg-red-500'}`} />

 <div className="flex flex-col md:flex-row items-center gap-10">
 <div className="relative w-40 h-40 shrink-0">
 <svg className="w-40 h-40 transform -rotate-90">
 <circle cx="80" cy="80" r="72" fill="none" stroke="#f1f5f9" strokeWidth="10" className="" />
 <circle cx="80" cy="80" r="72" fill="none"
 stroke={result.risk_level === 'low' ? '#22c55e' : result.risk_level === 'moderate' ? '#f59e0b' : '#ef4444'}
 strokeWidth="10" strokeDasharray={`${(result.risk_score / 100) * 452.4} 452.4`} strokeLinecap="round" className="transition-all duration-1000 ease-out" />
 </svg>
 <div className="absolute inset-0 flex flex-col items-center justify-center">
 <span className="text-4xl font-black text-slate-900 ">{result.risk_score}</span>
 <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Score</span>
 </div>
 </div>

 <div className="flex-1 text-center md:text-left">
 <div className={`inline-block px-3 py-1 rounded-full text-xs font-bold uppercase tracking-widest mb-3 ${result.risk_level === 'low' ? 'bg-green-50 text-green-600 ' : result.risk_level === 'moderate' ? 'bg-yellow-50 text-yellow-600 ' : 'bg-red-50 text-red-600 '}`}>
 {result.risk_level} Risk Level
 </div>
 <h2 className="text-2xl font-bold text-slate-900 mb-2">Overall Wellbeing Summary</h2>
 <p className="text-slate-500 font-light leading-relaxed">
 Our AI calculates a {(result.depression_probability * 100).toFixed(1)}% probability of depressive symptoms based on current lifestyle indicators.
 {result.risk_level === 'low' ? ' Keep up the great habits!' : ' We recommend focusing on the key factors identified below.'}
 </p>
 </div>
 </div>
 </div>

 <div className="grid md:grid-cols-2 gap-8">
 {result.top_factors?.length > 0 && (
 <div className="bg-white/70 backdrop-blur-2xl rounded-[2rem] shadow-[0_8px_40px_-12px_rgba(0,0,0,0.1)] border border-white/60 p-6">
 <h3 className="text-base font-bold text-slate-900 mb-6 flex items-center gap-2">
 <AlertTriangle size={18} className="text-yellow-500" /> Primary Risk Drivers
 </h3>
 <div className="space-y-4">
 {result.top_factors.map((f: any, i: number) => (
 <div key={i} className="flex items-center justify-between p-4 rounded-2xl bg-slate-50 border border-slate-100 group hover:border-blue-200 transition-all">
 <div>
 <p className="text-slate-900 text-sm font-bold">{f.feature}</p>
 <p className="text-slate-400 text-xs font-light">{f.description}</p>
 </div>
 <span className={`px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-tighter ${f.impact === 'high' ? 'bg-red-100 text-red-700 ' : f.impact === 'medium' ? 'bg-yellow-100 text-yellow-700 ' : 'bg-blue-100 text-blue-700 '}`}>{f.impact}</span>
 </div>
 ))}
 </div>
 </div>
 )}

 <div className="bg-white/70 backdrop-blur-2xl rounded-[2rem] shadow-[0_8px_40px_-12px_rgba(0,0,0,0.1)] border border-white/60 p-6">
 <h3 className="text-base font-bold text-slate-900 mb-6 flex items-center gap-2">
 <Sparkles size={18} className="text-[#1e40af]" /> Prescribed Interventions
 </h3>
 <div className="space-y-4">
 {result.recommendations.map((rec: string, i: number) => (
 <div key={i} className="flex items-start gap-4">
 <div className="w-8 h-8 rounded-xl bg-blue-50 flex items-center justify-center flex-shrink-0 mt-0.5 border border-blue-100 ">
 <span className="text-blue-600 text-xs font-black">{i + 1}</span>
 </div>
 <p className="text-sm text-slate-600 leading-relaxed font-light">{rec}</p>
 </div>
 ))}
 </div>
 </div>
 </div>

 <div className="flex flex-col sm:flex-row gap-4 pt-4">
 <button onClick={() => { setPhase('form'); setResult(null); setWizardStep(0); }} className="flex-1 btn-outline !py-4">Retake Assessment</button>
 <button onClick={() => router.push('/dashboard')} className="flex-1 btn-primary !py-4 shadow-xl shadow-[#1e40af]/20">Unlock Dashboard Insights</button>
 </div>
 </div>
 );
 }

 // ─── Multi-Step Wizard ───
 const isLast = wizardStep === STEPS.length - 1;
 const currentStep = STEPS[wizardStep];
 const progress = ((wizardStep + 1) / STEPS.length) * 100;

 return (
 <div className="max-w-3xl mx-auto pb-12 animate-fade-in-up">
 {/* Header */}
 <div className="mb-8">
 <motion.h1
 initial={{ opacity: 0, y: 20 }}
 animate={{ opacity: 1, y: 0 }}
 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900 mb-2 leading-tight"
 >Mental Health Diagnostic</motion.h1>
 <p className="text-slate-500 text-sm sm:text-base font-light">Complete each section to receive your AI-powered clinical assessment.</p>
 </div>

 {error && <div className="mb-6 p-4 rounded-2xl bg-red-50 border border-red-100 text-red-600 text-sm font-medium">{error}</div>}

 {/* Progress Bar */}
 <div className="mb-8">
 <div className="flex items-center justify-between mb-3">
 {STEPS.map((s, i) => (
 <button
 key={i}
 onClick={() => { setDirection(i > wizardStep ? 1 : -1); setWizardStep(i); }}
 className={`flex items-center gap-2 group transition-all ${i <= wizardStep ? 'opacity-100' : 'opacity-40'}`}
 >
 <div className={`w-9 h-9 rounded-xl flex items-center justify-center text-sm font-bold transition-all duration-300 ${i < wizardStep ? 'bg-green-100 text-green-600 ' :
 i === wizardStep ? 'text-white shadow-lg' :
 'bg-slate-100 text-slate-400'
 }`} style={i === wizardStep ? { backgroundColor: s.color } : undefined}>
 {i < wizardStep ? <CheckCircle size={18} /> : i + 1}
 </div>
 <span className="hidden md:block text-xs font-bold text-slate-600 group-hover:text-slate-900 transition-colors">{s.title}</span>
 </button>
 ))}
 </div>
 <div className="h-1.5 bg-slate-100 rounded-full overflow-hidden">
 <motion.div
 className="h-full rounded-full"
 style={{ backgroundColor: currentStep.color }}
 initial={false}
 animate={{ width: `${progress}%` }}
 transition={{ duration: 0.4, ease: 'easeInOut' }}
 />
 </div>
 </div>

 {/* Step Content Card */}
 <div className="bg-white/70 backdrop-blur-2xl rounded-[2rem] shadow-[0_8px_40px_-12px_rgba(0,0,0,0.1)] border border-white/60 p-8 sm:p-10 relative overflow-hidden min-h-[380px]">
 {/* Step Header inside card */}
 <div className="flex items-center gap-4 mb-8">
 <div className="w-12 h-12 rounded-2xl flex items-center justify-center" style={{ backgroundColor: `${currentStep.color}10`, color: currentStep.color }}>
 <currentStep.icon size={24} />
 </div>
 <div>
 <h3 className="text-xl font-bold text-slate-900 ">{currentStep.title}</h3>
 <p className="text-xs text-slate-400 font-medium">{currentStep.subtitle}</p>
 </div>
 <div className="ml-auto px-3 py-1.5 rounded-full bg-slate-100 text-[10px] font-black text-slate-500 uppercase tracking-widest">
 Step {wizardStep + 1}/{STEPS.length}
 </div>
 </div>

 {/* Animated Step Content */}
 <AnimatePresence mode="wait" custom={direction}>
 <motion.div
 key={wizardStep}
 custom={direction}
 variants={slideVariants}
 initial="enter"
 animate="center"
 exit="exit"
 transition={{ duration: 0.3, ease: [0.25, 0.46, 0.45, 0.94] }}
 >
 {wizardStep === 0 && (
 <div className="grid sm:grid-cols-2 gap-8">
 <InputField label="Student Age" type="number" value={form.age} onChange={(v: string) => update('age', parseInt(v) || '')} min={13} max={60} />
 <div>
 <label className="block text-sm font-bold text-slate-900 mb-2.5 uppercase tracking-wide">Biological Gender</label>
 <select value={form.gender} onChange={(e) => update('gender', e.target.value)} className="w-full px-4 py-3.5 rounded-xl bg-slate-50 border border-slate-200 text-slate-900 focus:outline-none focus:ring-4 focus:ring-blue-500/10 transition-all">
 <option value="Male">Male</option><option value="Female">Female</option>
 </select>
 </div>
 <div className="sm:col-span-2">
 <label className="block text-sm font-bold text-slate-900 mb-2.5 uppercase tracking-wide">Academic Faculty</label>
 <select value={form.department} onChange={(e) => update('department', e.target.value)} className="w-full px-4 py-3.5 rounded-xl bg-slate-50 border border-slate-200 text-slate-900 focus:outline-none focus:ring-4 focus:ring-blue-500/10 transition-all">
 {departments.map(d => <option key={d} value={d}>{d}</option>)}
 </select>
 </div>
 </div>
 )}
 {wizardStep === 1 && (
 <div className="grid sm:grid-cols-2 gap-10">
 <SliderField label="Cumulative GPA" icon={TrendingUp} value={form.cgpa} onChange={(v: number) => update('cgpa', v)} min={0} max={4} step={0.1} unit="" />
 <SliderField label="Study Velocity" icon={BookOpen} value={form.study_hours} onChange={(v: number) => update('study_hours', v)} min={0} max={18} step={0.5} unit="hrs/day" />
 <SliderField label="Workload Density" icon={Activity} value={form.academic_workload} onChange={(v: number) => update('academic_workload', v)} min={1} max={10} step={1} unit="/10" />
 <SliderField label="Exam Anxiety" icon={ShieldAlert} value={form.exam_anxiety} onChange={(v: number) => update('exam_anxiety', v)} min={1} max={10} step={1} unit="/10" />
 <div className="sm:col-span-2">
 <SliderField label="Academic Peer Pressure" icon={Users2} value={form.peer_pressure} onChange={(v: number) => update('peer_pressure', v)} min={1} max={10} step={1} unit="/10" />
 </div>
 </div>
 )}
 {wizardStep === 2 && (
 <div className="grid sm:grid-cols-2 gap-10">
 <SliderField label="Gaming Addiction Scale" icon={Gamepad2} value={form.gaming_behavior_score} onChange={(v: number) => update('gaming_behavior_score', v)} min={1} max={10} step={1} unit="/10" />
 <SliderField label="Social Addiction Scale" icon={Smartphone} value={form.social_media_addiction} onChange={(v: number) => update('social_media_addiction', v)} min={1} max={10} step={1} unit="/10" />
 </div>
 )}
 {wizardStep === 3 && (
 <div className="grid sm:grid-cols-2 gap-10">
 <SliderField label="Circadian Sleep" icon={Moon} value={form.sleep_duration} onChange={(v: number) => update('sleep_duration', v)} min={0} max={16} step={0.5} unit="hrs" />
 <SliderField label="Digital Exposure" icon={Smartphone} value={form.social_media_hours} onChange={(v: number) => update('social_media_hours', v)} min={0} max={16} step={0.5} unit="hrs" />
 <SliderField label="Physical Load" icon={Dumbbell} value={form.physical_activity} onChange={(v: number) => update('physical_activity', v)} min={0} max={300} step={10} unit="min/wk" />
 <SliderField label="Gaming Velocity" icon={Gamepad2} value={form.gaming_hours} onChange={(v: number) => update('gaming_hours', v)} min={0} max={16} step={0.5} unit="hrs/day" />
 <div className="sm:col-span-2">
 <SliderField label="Perceived Stress" icon={Gauge} value={form.stress_level} onChange={(v: number) => update('stress_level', v)} min={1} max={10} step={1} unit="/10" />
 </div>
 </div>
 )}
 </motion.div>
 </AnimatePresence>
 </div>

 {/* Navigation Buttons */}
 <div className="flex items-center justify-between mt-8 gap-4">
 <button
 onClick={goPrev}
 disabled={wizardStep === 0}
 className="flex items-center gap-2 px-6 py-3.5 rounded-xl text-sm font-bold text-slate-600 bg-white border border-slate-200 hover:bg-slate-50 disabled:opacity-30 disabled:cursor-not-allowed transition-all group"
 >
 <ArrowLeft size={16} className="group-hover:-translate-x-0.5 transition-transform" /> Previous
 </button>

 {isLast ? (
 <button
 onClick={handleSubmit}
 className="flex items-center gap-2 px-8 py-3.5 rounded-xl text-sm font-bold text-white bg-slate-900 hover:bg-blue-700 shadow-xl shadow-blue-600/20 transition-all active:scale-[0.98] group"
 >
 Evaluate Clinical Risk <ArrowRight size={16} className="group-hover:translate-x-0.5 transition-transform" />
 </button>
 ) : (
 <button
 onClick={goNext}
 className="flex items-center gap-2 px-8 py-3.5 rounded-xl text-sm font-bold text-white shadow-lg transition-all active:scale-[0.98] group"
 style={{ backgroundColor: currentStep.color }}
 >
 Continue <ChevronRight size={16} className="group-hover:translate-x-0.5 transition-transform" />
 </button>
 )}
 </div>
 </div>
 );
}

function InputField({ label, type, value, onChange, min, max }: any) {
 return (
 <div>
 <label className="block text-sm font-bold text-slate-900 mb-2.5 uppercase tracking-wide">{label}</label>
 <input type={type} value={Number.isNaN(value) || value === undefined ? '' : value} onChange={(e) => onChange(e.target.value)} min={min} max={max}
 className="w-full px-4 py-3.5 rounded-xl bg-slate-50 border border-slate-200 text-slate-900 focus:outline-none focus:ring-4 focus:ring-blue-500/10 transition-all font-medium" />
 </div>
 );
}

function SliderField({ label, icon: Icon, value, onChange, min, max, step, unit }: any) {
 return (
 <div className="group">
 <label className="flex items-center justify-between text-[11px] font-black uppercase tracking-widest text-slate-500 mb-3">
 <span className="flex items-center gap-2 group-hover:text-slate-900 transition-colors"><Icon size={14} /> {label}</span>
 <span className="text-blue-600 bg-blue-50 px-2 py-0.5 rounded-lg border border-blue-100 ">{value} {unit}</span>
 </label>
 <input type="range" min={min} max={max} step={step} value={value} onChange={(e) => onChange(parseFloat(e.target.value))} className="w-full cursor-pointer" />
 </div>
 );
}
