'use client';
import { useState } from 'react';
import { useAuth } from '@/lib/auth-context';
import { predictAPI } from '@/lib/api';
import { useRouter } from 'next/navigation';
import { Activity, Brain, Heart, Moon, BookOpen, Smartphone, Dumbbell, Gauge, AlertTriangle, CheckCircle, Loader2, Sparkles, TrendingUp, ArrowRight, Gamepad2, Users2, ShieldAlert } from 'lucide-react';

const departments = ['Engineering', 'Science', 'Medical', 'Arts', 'Business', 'Law', 'Education', 'Social Sciences'];

export default function AssessmentPage() {
    const { token } = useAuth();
    const router = useRouter();
    const [step, setStep] = useState(0);
    const [result, setResult] = useState<any>(null);
    const [error, setError] = useState('');
    const [form, setForm] = useState({
        age: 20, gender: 'Male', department: 'Engineering',
        cgpa: 3.0, sleep_duration: 7, study_hours: 5,
        social_media_hours: 3, physical_activity: 60, stress_level: 5,
        // New extended fields
        gaming_hours: 1, gaming_behavior_score: 1, social_media_addiction: 1,
        academic_workload: 5, peer_pressure: 3, exam_anxiety: 4
    });

    const update = (key: string, val: any) => setForm(prev => ({ ...prev, [key]: val }));

    const handleSubmit = async () => {
        setStep(1);
        setError('');
        try {
            const res = await predictAPI.predict(form, token!);
            setResult(res);
            setStep(2);
        } catch (err: any) { setError(err.message); setStep(0); }
    };

    if (step === 1) {
        return (
            <div className="flex items-center justify-center min-h-[60vh] animate-fade-in-up">
                <div className="text-center max-w-sm mx-auto px-6">
                    <div className="w-20 h-20 mx-auto mb-8 rounded-[2rem] bg-[#1e40af]/5 flex items-center justify-center relative">
                        <div className="absolute inset-0 rounded-[2rem] border-2 border-[#1e40af]/10 animate-ping opacity-20" />
                        <Brain size={40} className="text-[#1e40af]" />
                    </div>
                    <h2 className="text-2xl font-bold text-[#0f172a] mb-3">AI Analysis in Progress</h2>
                    <p className="text-[#64748b] font-light leading-relaxed">Our clinical-grade engine is evaluating your behavioral data against our student mental health model.</p>
                    <div className="mt-8 flex justify-center gap-1.5">
                        <div className="w-2 h-2 rounded-full bg-[#1e40af] animate-bounce [animation-delay:-0.3s]" />
                        <div className="w-2 h-2 rounded-full bg-[#1e40af] animate-bounce [animation-delay:-0.15s]" />
                        <div className="w-2 h-2 rounded-full bg-[#1e40af] animate-bounce" />
                    </div>
                </div>
            </div>
        );
    }

    if (step === 2 && result) {
        return (
            <div className="max-w-4xl mx-auto space-y-8 animate-fade-in-up pb-12">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                    <div>
                        <h1 className="text-3xl font-bold tracking-tight text-[#0f172a] mb-1">Assessment Insights</h1>
                        <p className="text-[#64748b] text-sm font-light">Precision health report generated by SMILE-AI</p>
                    </div>
                    <div className="px-4 py-2 rounded-xl bg-white border border-[#e2e8f0] flex items-center gap-2 self-start sm:self-center">
                        <TrendingUp size={16} className="text-[#1e40af]" />
                        <span className="text-xs font-bold text-[#0f172a] uppercase tracking-wider">Stability: 92%</span>
                    </div>
                </div>

                <div className={`bg-white/70 backdrop-blur-2xl rounded-[2rem] shadow-[0_8px_40px_-12px_rgba(0,0,0,0.1)] border border-white/60 p-8 relative overflow-hidden group ${result.risk_level === 'low' ? 'border-green-100' : result.risk_level === 'moderate' ? 'border-yellow-100' : 'border-red-100'}`}>
                    <div className={`absolute top-0 right-0 w-32 h-32 -translate-y-1/2 translate-x-1/2 blur-2xl opacity-10 rounded-full ${result.risk_level === 'low' ? 'bg-green-500' : result.risk_level === 'moderate' ? 'bg-yellow-500' : 'bg-red-500'
                        }`} />

                    <div className="flex flex-col md:flex-row items-center gap-10">
                        <div className="relative w-40 h-40 shrink-0">
                            <svg className="w-40 h-40 transform -rotate-90">
                                <circle cx="80" cy="80" r="72" fill="none" stroke="#f1f5f9" strokeWidth="10" />
                                <circle cx="80" cy="80" r="72" fill="none"
                                    stroke={result.risk_level === 'low' ? '#22c55e' : result.risk_level === 'moderate' ? '#f59e0b' : '#ef4444'}
                                    strokeWidth="10" strokeDasharray={`${(result.risk_score / 100) * 452.4} 452.4`} strokeLinecap="round" className="transition-all duration-1000 ease-out" />
                            </svg>
                            <div className="absolute inset-0 flex flex-col items-center justify-center">
                                <span className="text-4xl font-black text-[#0f172a]">{result.risk_score}</span>
                                <span className="text-[10px] font-bold text-[#94a3b8] uppercase tracking-widest">Score</span>
                            </div>
                        </div>

                        <div className="flex-1 text-center md:text-left">
                            <div className={`inline-block px-3 py-1 rounded-full text-xs font-bold uppercase tracking-widest mb-3 ${result.risk_level === 'low' ? 'bg-green-50 text-green-600' : result.risk_level === 'moderate' ? 'bg-yellow-50 text-yellow-600' : 'bg-red-50 text-red-600'
                                }`}>
                                {result.risk_level} Risk Level
                            </div>
                            <h2 className="text-2xl font-bold text-[#0f172a] mb-2">Overall Wellbeing Summary</h2>
                            <p className="text-[#64748b] font-light leading-relaxed">
                                Our AI calculates a {(result.depression_probability * 100).toFixed(1)}% probability of depressive symptoms based on current lifestyle indicators.
                                {result.risk_level === 'low' ? ' Keep up the great habits!' : ' We recommend focusing on the key factors identified below.'}
                            </p>
                        </div>
                    </div>
                </div>

                <div className="grid md:grid-cols-2 gap-8">
                    {result.top_factors?.length > 0 && (
                        <div className="bg-white/70 backdrop-blur-2xl rounded-[2rem] shadow-[0_8px_40px_-12px_rgba(0,0,0,0.1)] border border-white/60 p-6">
                            <h3 className="text-base font-bold text-[#0f172a] mb-6 flex items-center gap-2">
                                <AlertTriangle size={18} className="text-yellow-500" /> Primary Risk Drivers
                            </h3>
                            <div className="space-y-4">
                                {result.top_factors.map((f: any, i: number) => (
                                    <div key={i} className="flex items-center justify-between p-4 rounded-2xl bg-[#f8fafc] border border-[#f1f5f9] group hover:border-[#1e40af]/20 transition-all">
                                        <div>
                                            <p className="text-[#0f172a] text-sm font-bold">{f.feature}</p>
                                            <p className="text-[#94a3b8] text-xs font-light">{f.description}</p>
                                        </div>
                                        <span className={`px-2.5 py-1 rounded-full text-[10px] font-black uppercase tracking-tighter ${f.impact === 'high' ? 'bg-red-100 text-red-700' : f.impact === 'medium' ? 'bg-yellow-100 text-yellow-700' : 'bg-blue-100 text-blue-700'
                                            }`}>{f.impact}</span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    <div className="bg-white/70 backdrop-blur-2xl rounded-[2rem] shadow-[0_8px_40px_-12px_rgba(0,0,0,0.1)] border border-white/60 p-6">
                        <h3 className="text-base font-bold text-[#0f172a] mb-6 flex items-center gap-2">
                            <Sparkles size={18} className="text-[#1e40af]" /> Prescribed Interventions
                        </h3>
                        <div className="space-y-4">
                            {result.recommendations.map((rec: string, i: number) => (
                                <div key={i} className="flex items-start gap-4">
                                    <div className="w-8 h-8 rounded-xl bg-[#1e40af]/5 flex items-center justify-center flex-shrink-0 mt-0.5 border border-[#1e40af]/5">
                                        <span className="text-[#1e40af] text-xs font-black">{i + 1}</span>
                                    </div>
                                    <p className="text-sm text-[#475569] leading-relaxed font-light">{rec}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>

                <div className="flex flex-col sm:flex-row gap-4 pt-4">
                    <button onClick={() => { setStep(0); setResult(null); }} className="flex-1 btn-outline !py-4">Retake Assessment</button>
                    <button onClick={() => router.push('/dashboard')} className="flex-1 btn-primary !py-4 shadow-xl shadow-[#1e40af]/20">Unlock Dashboard Insights</button>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-4xl mx-auto space-y-10 pb-12 animate-fade-in-up">
            <div className="max-w-xl">
                <h1 className="text-4xl font-bold tracking-tight text-[#0f172a] mb-2 leading-tight">Mental Health Diagnostic</h1>
                <p className="text-[#64748b] text-base font-light">Complete the comprehensive wellness audit below. Our AI provides clinical-grade predictions based on your multidimensional student profile.</p>
            </div>

            {error && <div className="p-4 rounded-2xl bg-red-50 border border-red-100 text-red-600 text-sm font-medium">{error}</div>}

            <div className="grid grid-cols-1 lg:grid-cols-1 gap-8">
                <div className="card-premium p-8 sm:p-10">
                    <h3 className="text-xl font-bold text-[#0f172a] mb-8 flex items-center gap-3">
                        <div className="w-10 h-10 rounded-2xl bg-[#1e40af]/5 flex items-center justify-center">
                            <Brain size={20} className="text-[#1e40af]" />
                        </div>
                        Clinical Profile
                    </h3>
                    <div className="grid sm:grid-cols-2 gap-8">
                        <InputField label="Student Age" type="number" value={form.age} onChange={(v: string) => update('age', parseInt(v) || '')} min={13} max={60} />
                        <div>
                            <label className="block text-sm font-bold text-[#0f172a] mb-2.5 uppercase tracking-wide">Biological Gender</label>
                            <select value={form.gender} onChange={(e) => update('gender', e.target.value)} className="w-full px-4 py-3.5 rounded-xl bg-[#f8fafc] border border-[#e2e8f0] text-[#0f172a] focus:outline-none focus:ring-4 focus:ring-[#1e40af]/10 transition-all">
                                <option value="Male">Male</option><option value="Female">Female</option>
                            </select>
                        </div>
                        <div className="sm:col-span-2">
                            <label className="block text-sm font-bold text-[#0f172a] mb-2.5 uppercase tracking-wide">Academic Faculty</label>
                            <select value={form.department} onChange={(e) => update('department', e.target.value)} className="w-full px-4 py-3.5 rounded-xl bg-[#f8fafc] border border-[#e2e8f0] text-[#0f172a] focus:outline-none focus:ring-4 focus:ring-[#1e40af]/10 transition-all">
                                {departments.map(d => <option key={d} value={d}>{d}</option>)}
                            </select>
                        </div>
                    </div>
                </div>

                <div className="card-premium p-8 sm:p-10">
                    <h3 className="text-xl font-bold text-[#0f172a] mb-8 flex items-center gap-3">
                        <div className="w-10 h-10 rounded-2xl bg-[#1e40af]/5 flex items-center justify-center">
                            <BookOpen size={20} className="text-[#1e40af]" />
                        </div>
                        Academic Rigor
                    </h3>
                    <div className="grid sm:grid-cols-2 gap-10">
                        <SliderField label="Cumulative GPA" icon={TrendingUp} value={form.cgpa} onChange={(v: number) => update('cgpa', v)} min={0} max={4} step={0.1} unit="" />
                        <SliderField label="Study Velocity" icon={BookOpen} value={form.study_hours} onChange={(v: number) => update('study_hours', v)} min={0} max={18} step={0.5} unit="hrs/day" />
                        <SliderField label="Workload Density" icon={Activity} value={form.academic_workload} onChange={(v: number) => update('academic_workload', v)} min={1} max={10} step={1} unit="/10" />
                        <SliderField label="Exam Anxiety" icon={ShieldAlert} value={form.exam_anxiety} onChange={(v: number) => update('exam_anxiety', v)} min={1} max={10} step={1} unit="/10" />
                        <div className="sm:col-span-2">
                            <SliderField label="Academic Peer Pressure" icon={Users2} value={form.peer_pressure} onChange={(v: number) => update('peer_pressure', v)} min={1} max={10} step={1} unit="/10" />
                        </div>
                    </div>
                </div>

                <div className="card-premium p-8 sm:p-10">
                    <h3 className="text-xl font-bold text-[#0f172a] mb-8 flex items-center gap-3">
                        <div className="w-10 h-10 rounded-2xl bg-orange-50 flex items-center justify-center">
                            <Gamepad2 size={20} className="text-orange-600" />
                        </div>
                        Digital Habits & Engagement
                    </h3>
                    <div className="grid sm:grid-cols-2 gap-10">
                        <SliderField label="Gaming Addiction Scale" icon={Gamepad2} value={form.gaming_behavior_score} onChange={(v: number) => update('gaming_behavior_score', v)} min={1} max={10} step={1} unit="/10" />
                        <SliderField label="Social Addiction Scale" icon={Smartphone} value={form.social_media_addiction} onChange={(v: number) => update('social_media_addiction', v)} min={1} max={10} step={1} unit="/10" />
                    </div>
                </div>

                <div className="card-premium p-8 sm:p-10">
                    <h3 className="text-xl font-bold text-[#0f172a] mb-8 flex items-center gap-3">
                        <div className="w-10 h-10 rounded-2xl bg-[#8b5cf6]/5 flex items-center justify-center">
                            <Heart size={20} className="text-[#8b5cf6]" />
                        </div>
                        Lifestyle Matrix
                    </h3>
                    <div className="grid sm:grid-cols-2 gap-x-12 gap-y-10">
                        <SliderField label="Circadian Sleep" icon={Moon} value={form.sleep_duration} onChange={(v: number) => update('sleep_duration', v)} min={0} max={16} step={0.5} unit="hrs" />
                        <SliderField label="Digital Exposure" icon={Smartphone} value={form.social_media_hours} onChange={(v: number) => update('social_media_hours', v)} min={0} max={16} step={0.5} unit="hrs" />
                        <SliderField label="Physical Load" icon={Dumbbell} value={form.physical_activity} onChange={(v: number) => update('physical_activity', v)} min={0} max={300} step={10} unit="min/wk" />
                        <SliderField label="Gaming Velocity" icon={Gamepad2} value={form.gaming_hours} onChange={(v: number) => update('gaming_hours', v)} min={0} max={16} step={0.5} unit="hrs/day" />
                        <SliderField label="Perceived Stress" icon={Gauge} value={form.stress_level} onChange={(v: number) => update('stress_level', v)} min={1} max={10} step={1} unit="/10" />
                    </div>
                </div>

                <button onClick={handleSubmit} className="w-full btn-primary !text-lg !py-5 !rounded-2xl shadow-2xl shadow-[#1e40af]/30 hover:shadow-none transition-all group">
                    Evaluate Clinical Risk <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
                </button>
            </div>
        </div>
    );
}

function InputField({ label, type, value, onChange, min, max }: any) {
    return (
        <div>
            <label className="block text-sm font-bold text-[#0f172a] mb-2.5 uppercase tracking-wide">{label}</label>
            <input type={type} value={Number.isNaN(value) || value === undefined ? '' : value} onChange={(e) => onChange(e.target.value)} min={min} max={max}
                className="w-full px-4 py-3.5 rounded-xl bg-[#f8fafc] border border-[#e2e8f0] text-[#0f172a] focus:outline-none focus:ring-4 focus:ring-[#1e40af]/10 transition-all font-medium" />
        </div>
    );
}

function SliderField({ label, icon: Icon, value, onChange, min, max, step, unit }: any) {
    return (
        <div className="group">
            <label className="flex items-center justify-between text-[11px] font-black uppercase tracking-widest text-[#64748b] mb-3">
                <span className="flex items-center gap-2 group-hover:text-[#0f172a] transition-colors"><Icon size={14} /> {label}</span>
                <span className="text-[#1e40af] bg-[#1e40af]/5 px-2 py-0.5 rounded-lg border border-[#1e40af]/10">{value} {unit}</span>
            </label>
            <input type="range" min={min} max={max} step={step} value={value} onChange={(e) => onChange(parseFloat(e.target.value))} className="w-full cursor-pointer" />
        </div>
    );
}
